Rename head_branch to merge_branch

diff --git a/.github/workflows/PR-into-next-version.yml b/.github/workflows/PR-into-next-version.yml
--- a/.github/workflows/PR-into-next-version.yml
+++ b/.github/workflows/PR-into-next-version.yml
@@ -28,27 +28,27 @@ jobs:
 
           # Calculate PR head branch name (the branch to merge) by substituting 'maintenance' for 'merge'
           head_branch=${{ github.ref_name }}
-          head_branch=${head_branch/#maintenance/merge}
-          echo "  PR head branch: $head_branch"
+          merge_branch=${head_branch/#maintenance/merge}
+          echo "  Merge branch (will be used as PR head): $merge_branch"
 
           echo ""
 
-          echo "Pushing ${{ github.ref_name }} to $head_branch"
+          echo "Pushing ${{ github.ref_name }} to $merge_branch"
 
-          # Create or update $head_branch
+          # Create or update $merge_branch
 
-          gh api --silent --method=POST -f ref="refs/heads/$head_branch" -f sha=${{ github.sha }} "/repos/$owner_and_repo/git/refs" ||
-            gh api --silent --method=PATCH -f sha=${{ github.sha }} "/repos/$owner_and_repo/git/refs/heads/$head_branch" ||
-            (echo "Could not push ${{ github.ref_name }} (${{ github.sha }}) to $head_branch" 1>&2 ; exit 1)
+          gh api --silent --method=POST -f ref="refs/heads/$merge_branch" -f sha=${{ github.sha }} "/repos/$owner_and_repo/git/refs" ||
+            gh api --silent --method=PATCH -f sha=${{ github.sha }} "/repos/$owner_and_repo/git/refs/heads/$merge_branch" ||
+            (echo "Could not push ${{ github.ref_name }} (${{ github.sha }}) to $merge_branch" 1>&2 ; exit 1)
 
           # Create PR if it does not exist yet
-          existing_pr_url=$(gh pr list --repo $owner_and_repo --head $head_branch --base $base_branch --json url --jq 'map(.url[]).[]')
+          existing_pr_url=$(gh pr list --repo $owner_and_repo --head $merge_branch --base $base_branch --json url --jq 'map(.url[]).[]')
           if [[ $existing_pr_url ]]
           then
-            echo "Pull request $head_branch -> $base_branch already exists at $existing_pr_url"
+            echo "Pull request $merge_branch -> $base_branch already exists at $existing_pr_url"
           else
-            echo "Creating a new pull request $head_branch -> $base_branch"
-            gh pr create --repo $owner_and_repo --head $head_branch --base $base_branch \
+            echo "Creating a new pull request $merge_branch -> $base_branch"
+            gh pr create --repo $owner_and_repo --head $merge_branch --base $base_branch \
               --title "Merge ${{ github.ref_name }} into $base_branch" \
               --body "This is an automatic PR which merges changes from \`${{ github.ref_name }}\` to \`$base_branch\`." \
               --assignee '${{ github.actor }}' \
